#!/bin/bash

cd /usr/lib/rechnungs-assistent

# if /app/bin is present change directory to it (because then we are in flatpak)
if [ -d "/app/bin" ]; then
    cd /app/bin
fi

# Check if any arguments were passed
if [ $# -eq 0 ]; then
    echo "Starting frontend..."
    ./invoice
    exit 0
fi

# Start generator with arguments
echo "Starting generator..."
python3 generator-html.py "$@"
